"""Exact library-vs-game attribution for SGD2FreeRes, straight from the PDB.

WHY THIS EXISTS. library_scope's byte lane matches functions against the
VC6/VS2003 static runtimes vendored for D2. SGD2FreeRes-GDI is built with the
VS2022 toolset (14.44), so that lane structurally cannot see its runtime: the
sweep classified 63 of 1,265 functions as library, which for a C++ binary with
statically linked STL is not a low number, it is a blind one.

We built this binary, so we have its PDB -- and a PDB records which COMPILAND
(object file / library) every function came from. That is ground truth, not a
heuristic: a function from libcpmt.lib IS the runtime, and a function from
sgd2fr's own objects is not.

Emits JSON: {rva, name, compiland, is_library} per function.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from comtypes.client import CreateObject, GetModule

SymTagCompiland = 2
SymTagFunction = 5

# A compiland path tells you what linked it in. Our code comes from the
# project's own object files; everything below is somebody else's runtime.
_LIB_MARKERS = (
    "libcpmt", "libcmt", "libucrt", "libvcruntime", "msvcrt", "vcruntime",
    "ucrt", "oldnames", "kernel32", "user32", "gdi32", "advapi32", "shell32",
    "ole32", "oleaut32", "uuid", "delayimp", "corelibc",
    # VS ships these as objects inside the CRT libs.
    "\\crt\\", "/crt/", "vc\\tools\\msvc", "vc/tools/msvc",
)


def is_library_compiland(path: str) -> bool:
    p = (path or "").lower()
    return any(m in p for m in _LIB_MARKERS)


def main(pdb: str, out: str) -> int:
    GetModule("msdia140.dll")
    from comtypes.gen import Dia2Lib  # noqa: E402  (generated by GetModule)

    src = CreateObject(Dia2Lib.DiaSource, interface=Dia2Lib.IDiaDataSource)
    src.loadDataFromPdb(pdb)
    session = src.openSession()
    scope = session.globalScope

    rows, seen = [], set()

    # Functions must be enumerated PER COMPILAND. Asking globalScope for
    # SymTagFunction returns every function with its lexicalParent reported as
    # the global scope, so all 784 came back attributed to "SGD2FreeRes" -- one
    # bucket, which is exactly no attribution at all while looking like data.
    #
    # comtypes also maps IDiaEnumSymbols without Python iteration: a plain
    # `for` over it yields nothing, silently, which reads as "the PDB has no
    # functions". Index both levels explicitly.
    def children(sym, tag):
        e = sym.findChildren(tag, None, 0)
        return [e.Item(i) for i in range(e.Count)]

    compilands = children(scope, SymTagCompiland)
    print(f"[dia] {len(compilands)} compilands")
    for comp_sym in compilands:
        try:
            comp = comp_sym.name or ""
        except Exception:
            comp = ""
        lib = is_library_compiland(comp)
        for f in children(comp_sym, SymTagFunction):
            try:
                rva = int(f.relativeVirtualAddress)
            except Exception:
                continue
            if not rva or rva in seen:
                continue
            seen.add(rva)
            try:
                name = f.name or ""
            except Exception:
                name = ""
            rec = {"rva": rva, "name": name, "compiland": comp,
                   "is_library": lib}
            # SOURCE LOCATION. The name alone is a summary; scoring generated
            # documentation against the ORIGINAL CODE needs the code, so record
            # the file and line span each function was compiled from. Ben's
            # standing rule for this corpus is that the original is the
            # measuring stick -- a judge given only a name cannot tell a plate
            # that describes the right function badly from one that describes it
            # well.
            try:
                length = int(f.length)
            except Exception:
                length = 0
            if length:
                try:
                    lines = session.findLinesByRVA(rva, length)
                    recs = [lines.Item(i) for i in range(lines.Count)]
                except Exception:
                    recs = []
                nums, src = [], ""
                for ln in recs:
                    try:
                        nums.append(int(ln.lineNumber))
                        src = src or (ln.sourceFile.fileName or "")
                    except Exception:
                        continue
                if nums:
                    rec["source_file"] = src
                    rec["line_start"] = min(nums)
                    rec["line_end"] = max(nums)
            rows.append(rec)

    rows.sort(key=lambda r: r["rva"])
    Path(out).write_text(json.dumps(rows, indent=1), encoding="utf-8")

    lib = sum(1 for r in rows if r["is_library"])
    print(f"functions with an RVA : {len(rows)}")
    print(f"  library compiland   : {lib}")
    print(f"  our code            : {len(rows) - lib}")

    comps = {}
    for r in rows:
        comps.setdefault(r["compiland"], [0, 0])
        comps[r["compiland"]][0] += 1
        comps[r["compiland"]][1] += 1 if r["is_library"] else 0
    print("\ntop compilands by function count:")
    for c, (n, l) in sorted(comps.items(), key=lambda kv: -kv[1][0])[:18]:
        tag = "LIB " if l else "GAME"
        print(f"  {tag} {n:5d}  {c[-92:]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
